version: '3.7'

services:
  it2-php8:
    image: it2-php8:dev
    container_name: bodytherapyprague
    build:
      context: ./docker
      target: it2-php8
      dockerfile: docker/Dockerfile.dev
    ports:
      - "82:80" # HOST_PORT:CONTAINER_PORT
    #    network_mode: "host" # sdileni localhost s hostem, pozor na konflikt portu, viz. apache.ports.conf a apache.vhost.conf, nefunguje na ios
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache.ports.conf:/etc/apache2/ports.conf
      - ./docker/apache.vhost.conf:/etc/apache2/sites-enabled/vhost.conf
  mysqldb:
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pokus
    volumes:
      - ./data/database:/var/lib/mysql
      - ./docker/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf

  #adminer:
  #  image: adminer
  #  ports:
  #    - 83:8080
